works
uqbar-dao/uqbar-core pull request #105
Opened 2022-07-29 17:48 UTC by martyr-binbex

Return hints in order they are processed

2022-07-30 22:28 UTC, dr-frmr commented
Is there any way to retarget this to the iota-typing branch (#100 )? Logan and I refactored large parts of zink there to make jetting work.

2022-08-18 00:38 UTC, tacryt-socryp requested changes
Please reflect the above changes and also rebase on master.

2022-08-18 00:38 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    +$  good      (unit (pair * hints))
I don't like that the return type here changed. It was factored into a `+body` as the result and an `+appendix` as all the metadata on purpose.

2022-08-18 00:38 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    =/  hit  [%cons u.hhed u.htal]^(welp q.u.p.hed q.u.p.tal)
unnecessary variable

2022-08-18 00:38 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    =/  res
unnecessary variable and incorrect indentation. just keep the outer `%_` and modify the hints inline

2022-08-18 00:38 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    =/  res  %_  $
same issue as before

2022-08-18 00:38 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    =/  res  %_  $
same issue as before

2022-08-18 00:38 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    =/  res  %_  $
same issue

2022-08-18 00:38 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    :-
Line is way too long and the longer line needs to come last.

2022-08-18 00:38 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    [%& ~ p.u.p.bod (welp hin q.u.p.bod)]^app
While using a function in this way is fine, I'd really like the hints to be in the appendix,

2022-11-21 17:06 UTC, closed without merging