Da/push pull
uqbar-dao/uqbar-core pull request #189
Opened 2022-10-05 01:00 UTC by tadad

2022-10-05 01:08 UTC, tadad commented on lib/zig/contracts/lib/fungible.hoon
> +      [to.act town-id.cart [%on-push id.from.cart amount.act]]~
`to.act` has to be a contract that implements `[%on-push from=id amount=@ud]`

2022-10-05 01:09 UTC, tadad commented on lib/zig/contracts/lib/fungible.hoon
> +        nonces=(pmap address @ud)      ::  necessary for gasless approves
this lets you do async `%pulls`. e.g. if you are doing payroll, you can sign N messages, and have all employees `%pull` them whenever

2022-10-05 01:19 UTC, tadad commented on lib/zig/contracts/lib/fungible.hoon
> +        nonces=(pmap address @ud)      ::  necessary for gasless approves
if you have just a single @ud as a nonce, then nonce=0 needs to take, then 1, then 2, etc. which really defeats the use case.

2022-10-05 01:20 UTC, tadad commented on lib/zig/contracts/lib/fungible.hoon
> +    ==
this is just an [ERC677](https://github.com/ethereum/EIPs/issues/677) implementation. very under-utilized EIP - ChainLink is the only thing I know that uses it off the top of my head.

2022-10-05 01:22 UTC, dr-frmr commented on lib/zig/contracts/lib/fungible.hoon
> +    ==
can we rename `data` to `calldata`, so as not to confuse it with `data.rice`?

2022-10-05 01:24 UTC, tadad commented on lib/zig/contracts/lib/fungible.hoon
> +    ==
it let's you send tokens *and* call a function in the same transaction. Normally have to do an `%approve` and then call the function you actually want, but with this, you can just call it once. I think most contracts *should* implement this as opposed to the `%approve` and `%take` pattern - e.g. an AMM will just have to put the relevant swap parameters in `data=*`. Of course, you can also implement this as a signature and a `%pull` (what uniswap does currently, mostly because ERC677 is not widely implemented on ETH) but this is much cleaner from both a ux and dev-ex perspective

2022-10-05 01:27 UTC, tadad commented on lib/zig/contracts/lib/fungible.hoon
> +    ==
@dr-frmr yes, done

2022-10-05 01:27 UTC, tadad commented on lib/zig/contracts/lib/fungible.hoon
> +      [to.act town-id.cart [%on-push id.from.cart amount.act calldata.act]]~
`to.act` has to be a contract that implements `[%on-push from=id amount=@ud data=*]`

2022-10-10 17:07 UTC, dr-frmr requested changes

2022-10-10 17:07 UTC, dr-frmr commented on lib/zig/contracts/lib/fungible.hoon
> +      =>((~(jab py nonces.giver) to.act succ) ->)
This could be written more concisely with `+gut`:

```
?>  .=  nonce.act
    +((~(gut by nonces.giver) to.act 0))
```

2022-10-10 17:07 UTC, dr-frmr commented on lib/zig/contracts/lib/fungible.hoon
> +        [%& salt.p.giv %account [amount.act ~ metadata.giver ~] - me.cart to.act town-id.cart]
Make sure you switch the old `@ud` nonce representation to `~` *everywhere* in the codebase. It's in the %give and %take arms, and it's also in the `zigs.hoon` contract, plus %wallet. plus `mill.hoon`. We need to match the fungible standard everywhere.

2022-10-10 17:07 UTC, dr-frmr commented on lib/zig/contracts/lib/fungible.hoon
> +        nonces    (~(jab py nonces.giver) to.act succ)
This is equivalent to doing `(~(put py nonces.giver) to.act nonce.act)` but uses more gas

2022-10-10 22:45 UTC, tadad commented on lib/zig/contracts/lib/fungible.hoon
> +        nonces    (~(jab py nonces.giver) to.act succ)
you do need to increment it so I think it would be `(~(put py nonces.giver) to.act +(nonce.act))`

2022-10-11 00:44 UTC, tadad commented on lib/zig/contracts/lib/fungible.hoon
> +        [%& salt.p.giv %account [amount.act ~ metadata.giver ~] - me.cart to.act town-id.cart]
Fixed in `fungible.hoon` and `zigs.hoon` - but I think the nonces in `%mill` and `%wallet` are different - those are nonces related to like "how many transactions have I already sent" not "how many `%pull`s have I let people perform"

2022-10-11 01:09 UTC, tadad commented
great all the issues should be resolved

2022-10-11 16:10 UTC, dr-frmr commented on lib/zig/contracts/lib/fungible.hoon
> +        nonces    (~(jab py nonces.giver) to.act succ)
Isn't `nonce.act` asserted to be equal to whatever nonce they *had* plus one, already? Therefore if you want the nonce incrementing by one each time, you'd just insert `nonce.act`

2022-10-11 16:11 UTC, dr-frmr commented on lib/zig/contracts/lib/fungible.hoon
> +        [%& salt.p.giv %account [amount.act ~ metadata.giver ~] - me.cart to.act town-id.cart]
I'm not talking about account nonces -- I'm talking about the data types that represent standard fungible tokens in wallet and mill

2022-10-11 16:12 UTC, dr-frmr commented on lib/zig/contracts/lib/fungible.hoon
> +        [%& salt.p.giv %account [amount.act ~ metadata.giver ~] - me.cart to.act town-id.cart]
https://github.com/uqbar-dao/ziggurat/blob/91d42d811bcca86c2acf3e0e9a963b92f557bc3a/lib/zig/mill.hoon#L204-L209

2022-10-11 16:13 UTC, dr-frmr commented on lib/zig/contracts/lib/fungible.hoon
> +        [%& salt.p.giv %account [amount.act ~ metadata.giver ~] - me.cart to.act town-id.cart]
https://github.com/uqbar-dao/ziggurat/blob/91d42d811bcca86c2acf3e0e9a963b92f557bc3a/sur/wallet.hoon#L123-L128

2022-10-11 16:17 UTC, dr-frmr requested changes

2022-10-11 16:17 UTC, dr-frmr commented on lib/zig/contracts/lib/fungible.hoon
> +      [to.act town-id.cart [%on-push id.from.cart amount.act calldata.act]]~
I'm realizing this design has a problem: if a contract wants to make use of this feature in an %on-push arm, they need to somehow keep a list of contract IDs which they know to correctly implement the fungible %push. In the current implementation, a malicious contract can *easily* produce an %on-push call, and the receiving contract has no way to verify if the tokens were actually given to them.

2022-10-11 16:20 UTC, dr-frmr commented on lib/zig/contracts/lib/fungible.hoon
> +      [to.act town-id.cart [%on-push id.from.cart amount.act calldata.act]]~
The way to fix this is to actually make use of the %pull process inside of a %push. The only way I can think of for a receiving contract to reliably verify their payment is to have them %pull tokens as a continuation -- there's no straightforward way to prove that you've just added some number to their token balance. So, a %push should set an allowance, issue a continuation call, and expect the receiving contract to immediately %pull that amount.

2022-10-11 16:21 UTC, tadad commented on lib/zig/contracts/lib/fungible.hoon
> +        nonces    (~(jab py nonces.giver) to.act succ)
not the way I have it right now because you have to compare the current nonce `0` to the incoming nonce (has to also be `0`), and then increment the current nonce. You could do it the other way where you compare `+(current-nonce)` to `incoming-nonce`. Either way would work but my way indexes from zero rather than 1 which I like.

2022-10-11 17:11 UTC, tadad commented on lib/zig/contracts/lib/fungible.hoon
> +      [to.act town-id.cart [%on-push id.from.cart amount.act calldata.act]]~
right - this is also a problem with ERC677. In practice what you have is usually just a whitelist of tokens that you will accept, and that you know are not malicious. E.g. Chainlink says the `%on-push` has to come from the LINK token, and nothing else is a valid payment. In the case of something like uniswap where you want to use the `%on-push` interface for all token pools, abusing the `on-push` is just creating a scam token. However, this is still not ideal, and fee-on-transfer tokens would complicate this.

Another pattern we could use is the `approveAndCall` which is discussed in the 677 post [here](https://github.com/ethereum/EIPs/issues/677#issuecomment-317118992). This means that the receiver contract has to `%take` the tokens, which fixes the problem you brought up - the receiver contract can verify that it got the tokens. It is also more flexible in that the contract can calculate the exact amount of tokens it needs, and only `%take` some of them.

Personally I like the `approveAndCall` pattern a lot - seems like a safe and ideal way to call contracts. If you're on board I can rewrite the `%push`/`%on-push` to match the `approveAndCall` pattern

2022-10-11 17:19 UTC, dr-frmr commented on lib/zig/contracts/lib/fungible.hoon
> +      [to.act town-id.cart [%on-push id.from.cart amount.act calldata.act]]~
Yep, approveAndCall looks exactly right. Funny to see them having basically the same conversation we are now, 5 years ago.

2022-10-12 18:28 UTC, tadad commented on lib/zig/contracts/lib/fungible.hoon
> +      [to.act town-id.cart [%on-push id.from.cart amount.act calldata.act]]~
just changed `%push` to be an `approveAndCall` implementation instead of a `transferAndCall` implementation

2022-10-12 21:31 UTC, dr-frmr commented
Sadly just realized that this change to the wallet's `token-account` type will lead to a modified state type for `wallet.hoon`.

You know what that means... `%state-1`

2022-10-12 21:34 UTC, dr-frmr commented
> Sadly just realized that this change to the wallet's `token-account` type will lead to a modified state type for `wallet.hoon`.

As well as needing a `%state-1` to migrate wallets from current token account type, we'll also need to keep a version of the *old* fungible token type in order to support the currently-deployed testnet tokens :/

2022-10-12 22:00 UTC, tadad commented
> > Sadly just realized that this change to the wallet's `token-account` type will lead to a modified state type for `wallet.hoon`.
> 
> As well as needing a `%state-1` to migrate wallets from current token account type, we'll also need to keep a version of the _old_ fungible token type in order to support

God damn, I'm seething

2022-10-13 01:37 UTC, dr-frmr commented
I know, it sucks :(

When we're ready to exit testnet world we can shut down all our old stuff and set up a new distribution. At that point we can wash away all the backwards compatibility and state transitions like tears in rain.

2022-10-26 19:36 UTC, dr-frmr approved these changes

2022-10-26 20:15 UTC, merged