Da/is ready
uqbar-dao/uqbar-core pull request #292
Opened 2022-11-21 22:21 UTC by tadad

2022-11-22 00:37 UTC, hosted-fornet requested changes
I like the approach. Left a few comments, main thing that must change before I'd be comfortable merging is cards returned in `+on-agent` `%ready` branch. Otherwise just readability and style comments.

2022-11-22 00:37 UTC, hosted-fornet commented on app/ziggurat.hoon
> +/-  spider, *pyro
Would prefer `pyro` import be namespaced.

2022-11-22 00:37 UTC, hosted-fornet commented on app/ziggurat.hoon
> +      ?.  (levy ~(val by pyro-ships-ready) |=(w=? =(w %.y)))
Might be easier/more readable to use `all:by`, e.g.,

```hoon
(~(all by pyro-ships-ready) |=(w=? w))
```

2022-11-22 00:37 UTC, hosted-fornet commented on app/ziggurat.hoon
> +      ==
Can probably just remove `%load-pyro-snapshot` entirely and have FE/users poke %pyro themselves. Only reason I can think of to keep it around is if we need to manipulate %ziggurat state, but we don't do that here.

2022-11-22 00:37 UTC, hosted-fornet commented on app/ziggurat.hoon
> +      ?.  (levy ~(val by pyro-ships-ready) |=(w=? =(w %.y)))
Same as above `+levy`,

```hoon
(~(all by pyro-ships-ready) |=(w=? w))
```

probably better.

2022-11-22 00:37 UTC, hosted-fornet commented on app/ziggurat.hoon
> +      ==
This should just check for non-null `test-queue` and pop off and run the first element of the queue (`i.test-queue`); subsequent items in the test queue will be processed as previous items finish, see https://github.com/uqbar-dao/uqbar-core/blob/7865d3471b25d80a31a8743942b256e6de70c3ab/app/ziggurat.hoon#L578-L585

2022-11-22 00:49 UTC, tadad commented on app/ziggurat.hoon
> +      ==
yeah agreed, let's take it out

2022-11-22 00:53 UTC, tadad commented on app/ziggurat.hoon
> +      ==
ahhh I see. We might want to change `test-queue` to a `qeu` because `snoc`ing has pretty bad performance

2022-11-22 01:23 UTC, hosted-fornet commented on app/ziggurat.hoon
> +      ==
I wouldn't be opposed to changing to a `qeu`, but I would say it is low priority. I've opened #296 so we don't lose track of this.

2022-11-22 03:58 UTC, hosted-fornet requested changes
Tested and it looks mostly good, with one exception: if I run a test before running %start-pyro-ships, it will try to run the thread, crash, and populate `running-test`. This breaks running future tests, even after running %start-pyro-ships, which will stack up in the queue and never run.

To get the crash:

```hoon
|meld

=zig -build-file /=zig=/sur/zig/ziggurat/hoon
=rollup-host ~nec
:ziggurat &ziggurat-action [%foo %new-project 0x1234.5678]

=setup-nec `test-steps:zig`~[[%dojo [rollup-host ':rollup|activate'] ~] [%dojo [rollup-host ':sequencer|init our 0x0 0xc9f8.722e.78ae.2e83.0dd9.e8b9.db20.f36a.1bc4.c704.4758.6825.c463.1ab6.daee.e608'] ~] [%poke [rollup-host %indexer %set-sequencer '[our %sequencer]'] ~] [%poke [rollup-host %indexer %set-rollup '[our %rollup]'] ~] [%poke [rollup-host %uqbar %wallet-poke '[%import-seed \'uphold apology rubber cash parade wonder shuffle blast delay differ help priority bleak ugly fragile flip surge shield shed mistake matrix hold foam shove\' \'squid\' \'nickname\']'] ~]]
=setup-bud `test-steps:zig`~[[%poke [~bud %indexer %set-sequencer '[~nec %sequencer]'] ~] [%poke [~bud %indexer %set-rollup '[~nec %rollup]'] ~] [%poke [~bud %indexer %indexer-bootstrap '[~nec %indexer]'] ~] [%poke [~bud %uqbar %wallet-poke '[%import-seed \'post fitness extend exit crack question answer fruit donkey quality emotion draw section width emotion leg settle bulb zero learn solution dutch target kidney\' \'squid\' \'nickname\']'] ~]]
=setup `test-steps:zig`(weld setup-nec setup-bud)
:ziggurat &ziggurat-action [%foo %add-test `%setup setup]

=setup-id 0xa253.baf1.f666.df41.ab31.fe25.2de6.5d20

:ziggurat &ziggurat-action [%foo %run-test setup-id]
```

One thing to change could be in %ziggurat's %thread-failed: modify that to change state and send `running-test` to `~`. However, that does not get to the route of the problem, which is that the test should be added to the `test-queue`, not run yet until %start-pyro-ships has completed.

2022-11-22 20:42 UTC, tadad commented
bug above is fixed as well as #296

2022-11-22 21:26 UTC, hosted-fornet requested changes
Test steps pre-startup are working properly now, but the change to qeu introduced a bug where queued up test steps do not get run after the currently running test step finishes.

2022-11-22 21:26 UTC, hosted-fornet commented on app/ziggurat.hoon
> +        `this(running-test ~)
:+1:

2022-11-22 21:26 UTC, hosted-fornet commented on app/ziggurat.hoon
> +      =/  top  ~(get to test-queue.this) :: XX why isn't =^ working
References here and above to `foo.this` should just be to `foo`.

2022-11-22 21:28 UTC, hosted-fornet commented
> Test steps pre-startup are working properly now, but the change to qeu introduced a bug where queued up test steps do not get run after the currently running test step finishes.

E.g. I am running the readme-pyro steps and copy-pasting in 
```
:ziggurat &ziggurat-action [%foo %run-test scry-bud-id]

:ziggurat &ziggurat-action [%foo %run-test scry-nec-id]

:ziggurat &ziggurat-action [%foo %run-test scry-clay-id]

:ziggurat &ziggurat-action [%foo %run-test send-nec-id]
```

after starting ships and only the first scry is run.

2022-11-22 23:04 UTC, hosted-fornet commented on app/ziggurat.hoon
> +      =/  wach=(list card:agent:gall)
Would be nice here to have a default of `~nec` and `~bud` if passed a `ships.act=~`, i.e. something like

```hoon
=?  ships.act  ~  ~[~nec ~bud]
```

2022-11-23 19:25 UTC, hosted-fornet requested changes
I am seeing queued tests get run more than once, and other things in queue not get run. Specifically, I ran:

```hoon
|meld

=zig -build-file /=zig=/sur/zig/ziggurat/hoon
=rollup-host ~nec
:ziggurat &ziggurat-action [%foo %new-project 0x1234.5678]

=setup-nec `test-steps:zig`~[[%dojo [rollup-host ':rollup|activate'] ~] [%dojo [rollup-host ':sequencer|init our 0x0 0xc9f8.722e.78ae.2e83.0dd9.e8b9.db20.f36a.1bc4.c704.4758.6825.c463.1ab6.daee.e608'] ~] [%poke [rollup-host %indexer %set-sequencer '[our %sequencer]'] ~] [%poke [rollup-host %indexer %set-rollup '[our %rollup]'] ~] [%poke [rollup-host %uqbar %wallet-poke '[%import-seed \'uphold apology rubber cash parade wonder shuffle blast delay differ help priority bleak ugly fragile flip surge shield shed mistake matrix hold foam shove\' \'squid\' \'nickname\']'] ~]]
=setup-bud `test-steps:zig`~[[%poke [~bud %indexer %set-sequencer '[~nec %sequencer]'] ~] [%poke [~bud %indexer %set-rollup '[~nec %rollup]'] ~] [%poke [~bud %indexer %indexer-bootstrap '[~nec %indexer]'] ~] [%poke [~bud %uqbar %wallet-poke '[%import-seed \'post fitness extend exit crack question answer fruit donkey quality emotion draw section width emotion leg settle bulb zero learn solution dutch target kidney\' \'squid\' \'nickname\']'] ~]]
=setup `test-steps:zig`(weld setup-nec setup-bud)
:ziggurat &ziggurat-action [%foo %add-test `%setup setup]
=scry-nec `test-steps:zig`~[[%scry [~nec /zig/sur/zig/indexer/hoon 'update:indexer' %gx %indexer /batch-order/0x0/noun] '[%batch-order batch-order=~[0xd85a.d919.9806.cbc2.b841.eb0d.854d.22af]]']]
:ziggurat &ziggurat-action [%foo %add-test `%scry-nec scry-nec]
=scry-bud `test-steps:zig`~[[%scry [~bud /zig/sur/zig/indexer/hoon 'update:indexer' %gx %indexer /batch-order/0x0/noun] '[%batch-order batch-order=~[0xd85a.d919.9806.cbc2.b841.eb0d.854d.22af]]']]
:ziggurat &ziggurat-action [%foo %add-test `%scry-bud scry-bud]
=scry-clay `test-steps:zig`~[[%scry [~bud ~ 'wain' %cx %base /desk/bill] '<|acme azimuth dbug dojo eth-watcher hood herm lens ping spider|>']]
:ziggurat &ziggurat-action [%foo %add-test `%scry-clay scry-clay]
=send-nec `test-steps:zig`~[[%poke [rollup-host %uqbar %wallet-poke '[%transaction from=0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70 contract=0x74.6361.7274.6e6f.632d.7367.697a town=0x0 action=[%give to=0xd6dc.c8ff.7ec5.4416.6d4e.b701.d1a6.8e97.b464.76de amount=123.456 item=0x89a0.89d8.dddf.d13a.418c.0d93.d4b4.e7c7.637a.d56c.96c0.7f91.3a14.8174.c7a7.71e6]]'] ~] [%poke [rollup-host %uqbar %wallet-poke '[%submit from=0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70 hash=0xa99c.4c8e.1c8d.abb8.e870.81e8.8c96.2cf5 gas=[rate=1 bud=1.000.000]]'] ~] [%dojo [~nec ':sequencer|batch'] `(list test-read-step:zig)`~[[%scry [~nec /zig/sur/zig/indexer/hoon 'update:indexer' %gx %indexer /newest/item/0x89a0.89d8.dddf.d13a.418c.0d93.d4b4.e7c7.637a.d56c.96c0.7f91.3a14.8174.c7a7.71e6/noun] '']]]]
:ziggurat &ziggurat-action [%foo %add-test `%send-nec send-nec]

=setup-id 0xa253.baf1.f666.df41.ab31.fe25.2de6.5d20
=scry-nec-id 0x9fb7.15f6.364d.dfd0.42ea.540e.57cd.daf8
=scry-bud-id 0xddd5.d31d.72c2.dbe0.42fe.7ae1.3d17.8db5
=scry-clay-id 0x29de.35b5.a26d.c49c.a39c.7437.c399.c316
=send-nec-id 0xa2d1.13bb.100c.267f.9357.209d.d428.c33e

:ziggurat &ziggurat-action [%foo %run-test setup-id]

:ziggurat &ziggurat-action [%foo %run-test scry-bud-id]

:ziggurat &ziggurat-action [%foo %run-test scry-nec-id]

:ziggurat &ziggurat-action [%foo %run-test scry-clay-id]

:ziggurat &ziggurat-action [%foo %run-test send-nec-id]

:ziggurat &ziggurat-action [%foo %start-pyro-ships ~]
```

and saw the `setup` step run 3 times, then the `scry-clay`, then the `send-nec`: the intermediate `scry-bud` and `scry-nec` appear to have been skipped, and the `setup` run instead.

2022-11-23 19:27 UTC, hosted-fornet commented
(I  just copy-paste that entire codeblock into the Dojo)

2022-11-23 23:04 UTC, hosted-fornet requested changes
Nice work simplifying the state and logic. Almost there.

2022-11-23 23:04 UTC, hosted-fornet commented on app/ziggurat.hoon
>        =/  =project  (~(got by projects) project.act)
Let's change this to be below 390 and use `top` to pull the project. Then we just discard whatever `project.act` we get passed here and use the proper value we pop off the queue. Below we should pass a dummy bunted `%$` or `''` into `%run-queue` calls. This is annoying, but because `project.act` is included in every action, we should just pass the bunted value for now. So it would look something like:

```hoon
=^  top  test-queue  ~(get to test-queue)
=*  project-id  -.top
=*  test-id  +.top
=/  =project  (~(got by projects) project-id)
=/  =test  (~(got by tests.project) test-id)
```

The reason I want to do it this way is that it we have the info in the queue anyways, so should not just use that as a source of truth; otherwise we have to be careful when we are calling %run-queue elsewhere that we examine the top of the queue and use that project-id -- we are going to pop off the queue in here anyways so why not skip that step?

2022-11-23 23:04 UTC, hosted-fornet commented on app/ziggurat.hoon
> +            ?^(name.test u.name.test (scot %ux +.top))
Would prefer that you `=*` to give a meaningful name to `+.top` rather than using it raw.

2022-11-23 23:04 UTC, hosted-fornet commented on app/ziggurat.hoon
> +      :_  state(test-queue test-queue) :: XX might be wrong?
Can just have

```hoon
:_  state
```

because you modify `test-queue` above in line 390 with the `=^`

2022-11-23 23:04 UTC, hosted-fornet commented on app/ziggurat.hoon
> +        %queue-test
Used to have `%add-test`, `%run-test`, and `%add-and-run-test`. This is taking the place of `%add-and-run-test`, but am now missing the ability to queue a test that has already been added to state. I'd suggest changing the name of this branch to `%add-and-queue-test` and adding another branch called `%queue-test` that accepts a `test-id` and runs it if found in state.

2022-11-23 23:04 UTC, hosted-fornet commented on app/ziggurat.hoon
> +        [%pass /ready/[project.act]/(scot %p who) %agent [our.bowl %pyro] %leave ~]
This `%leave` should probably either happen:

1. as we receive the `%ready` sub updates in `%+on-agent`, or
2. %pyro should issue a %kick at the same time it sends `%ready`

2022-11-23 23:04 UTC, hosted-fornet commented on app/ziggurat.hoon
> +        $(ships.act t.ships.act, r (~(put by r) i.ships.act %.n))
replace with

```hoon
(~(gas by *(map ship ?)) ships.act)
```

2022-11-23 23:04 UTC, hosted-fornet commented on app/ziggurat.hoon
> +        ~&  >  "%test-done"
Please remove debugging ~&s before merge.

2022-11-23 23:04 UTC, hosted-fornet commented on app/ziggurat.hoon
> +          !>([project-name %run-queue ~]) :: XX why not faces
Not sure what this comment means?

Also: we should pass a dummy `%$` value into `%run-queue`. See comment above in `%run-queue`.

2022-11-23 23:04 UTC, hosted-fornet commented on app/ziggurat.hoon
> +      ::     something on a subscribe wire that says "your ships are ready sir"
I think the code as written is probably the proper behavior. If the user has queued up tests, the intent is clearly that they be run, and if we have to get stuff ready on backend, we should run them when we can.

2022-11-23 23:04 UTC, hosted-fornet commented on app/ziggurat.hoon
> +      !>([project %run-queue ~])
We should pass a dummy `%$` value into `%run-queue`. See comment above in `%run-queue`. As a result, we can change these wires back to `/ready/[who]`.

2022-11-23 23:37 UTC, tadad commented on app/ziggurat.hoon
> +            ?^(name.test u.name.test (scot %ux +.top))
done

2022-11-24 15:50 UTC, tadad commented on app/ziggurat.hoon
> +        [%pass /ready/[project.act]/(scot %p who) %agent [our.bowl %pyro] %leave ~]
done

2022-11-24 15:51 UTC, tadad commented on app/ziggurat.hoon
> +        [%pass /ready/[project.act]/(scot %p who) %agent [our.bowl %pyro] %leave ~]
did it as 1. because some other apps in the future might use pyro, and they might not want to get kicked on ready

2022-11-24 15:53 UTC, tadad commented on app/ziggurat.hoon
> +        ~&  >  "%test-done"
I actually think we might want this - when working in just the dojo it's hard to see what test is being run and if it was run successfully. This should probably read something like "%ziggurat test-id 0x1234.6543 done"

2022-11-24 16:05 UTC, tadad commented on app/ziggurat.hoon
>        =/  =project  (~(got by projects) project.act)
okay sure
I can see an issue arising where the you'd want multiple queues for multiple projects - like if you are switching between two projects you might back up the queue with tests from project A and forgetting to empty it before switching to project B. If people are having an issue with that in the future we should probably change it to be `test-queue=(map project=@ta q=qeu)`. Not going to over engineer it right now though

2022-11-24 16:41 UTC, tadad commented on app/ziggurat.hoon
> +        $(ships.act t.ships.act, r (~(put by r) i.ships.act %.n))
done:
```
%-  ~(gas by *(map ship ?))
(turn ships.act |=(=ship [ship %.n]))
```

2022-11-24 20:16 UTC, hosted-fornet commented on app/ziggurat.hoon
> +        $(ships.act t.ships.act, r (~(put by r) i.ships.act %.n))
Ah, yeah, my suggested code was wrong, sorry about that.

2022-11-24 20:16 UTC, hosted-fornet commented on app/ziggurat.hoon
> +        ~&  >  "%test-done"
Okay, I am fine with this :+1:

2022-11-24 20:16 UTC, hosted-fornet commented on app/ziggurat.hoon
>        =/  =project  (~(got by projects) project.act)
Hmm, good point. I had been imagining that we should pretty aggressively be clearing out the queue. E.g. the FE might always %run-queue whenever adding to queue. See comment on main thread below.

2022-11-24 20:16 UTC, hosted-fornet requested changes
One thing that is still not quite right is the `%run-test` behavior. E.g. if you do:

```hoon
|meld

=zig -build-file /=zig=/sur/zig/ziggurat/hoon
=rollup-host ~nec
:ziggurat &ziggurat-action [%foo %new-project 0x1234.5678]

=setup-nec `test-steps:zig`~[[%dojo [rollup-host ':rollup|activate'] ~] [%dojo [rollup-host ':sequencer|init our 0x0 0xc9f8.722e.78ae.2e83.0dd9.e8b9.db20.f36a.1bc4.c704.4758.6825.c463.1ab6.daee.e608'] ~] [%poke [rollup-host %indexer %set-sequencer '[our %sequencer]'] ~] [%poke [rollup-host %indexer %set-rollup '[our %rollup]'] ~] [%poke [rollup-host %uqbar %wallet-poke '[%import-seed \'uphold apology rubber cash parade wonder shuffle blast delay differ help priority bleak ugly fragile flip surge shield shed mistake matrix hold foam shove\' \'squid\' \'nickname\']'] ~]]
=setup-bud `test-steps:zig`~[[%poke [~bud %indexer %set-sequencer '[~nec %sequencer]'] ~] [%poke [~bud %indexer %set-rollup '[~nec %rollup]'] ~] [%poke [~bud %indexer %indexer-bootstrap '[~nec %indexer]'] ~] [%poke [~bud %uqbar %wallet-poke '[%import-seed \'post fitness extend exit crack question answer fruit donkey quality emotion draw section width emotion leg settle bulb zero learn solution dutch target kidney\' \'squid\' \'nickname\']'] ~]]
=setup `test-steps:zig`(weld setup-nec setup-bud)
:ziggurat &ziggurat-action [%foo %add-test `%setup setup]
=scry-nec `test-steps:zig`~[[%scry [~nec /zig/sur/zig/indexer/hoon 'update:indexer' %gx %indexer /batch-order/0x0/noun] '[%batch-order batch-order=~[0xd85a.d919.9806.cbc2.b841.eb0d.854d.22af]]']]
:ziggurat &ziggurat-action [%foo %add-test `%scry-nec scry-nec]
=scry-bud `test-steps:zig`~[[%scry [~bud /zig/sur/zig/indexer/hoon 'update:indexer' %gx %indexer /batch-order/0x0/noun] '[%batch-order batch-order=~[0xd85a.d919.9806.cbc2.b841.eb0d.854d.22af]]']]
:ziggurat &ziggurat-action [%foo %add-test `%scry-bud scry-bud]
=scry-clay `test-steps:zig`~[[%scry [~bud ~ 'wain' %cx %base /desk/bill] '<|acme azimuth dbug dojo eth-watcher hood herm lens ping spider|>']]
:ziggurat &ziggurat-action [%foo %add-test `%scry-clay scry-clay]
=send-nec `test-steps:zig`~[[%poke [rollup-host %uqbar %wallet-poke '[%transaction from=0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70 contract=0x74.6361.7274.6e6f.632d.7367.697a town=0x0 action=[%give to=0xd6dc.c8ff.7ec5.4416.6d4e.b701.d1a6.8e97.b464.76de amount=123.456 item=0x89a0.89d8.dddf.d13a.418c.0d93.d4b4.e7c7.637a.d56c.96c0.7f91.3a14.8174.c7a7.71e6]]'] ~] [%poke [rollup-host %uqbar %wallet-poke '[%submit from=0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70 hash=0xa99c.4c8e.1c8d.abb8.e870.81e8.8c96.2cf5 gas=[rate=1 bud=1.000.000]]'] ~] [%dojo [~nec ':sequencer|batch'] `(list test-read-step:zig)`~[[%scry [~nec /zig/sur/zig/indexer/hoon 'update:indexer' %gx %indexer /newest/item/0x89a0.89d8.dddf.d13a.418c.0d93.d4b4.e7c7.637a.d56c.96c0.7f91.3a14.8174.c7a7.71e6/noun] '']]]]
:ziggurat &ziggurat-action [%foo %add-test `%send-nec send-nec]
=send-nec-custom `test-steps:zig`~[[%custom-write %poke-wallet-transaction '[who=~nec contract=0x74.6361.7274.6e6f.632d.7367.697a transaction=\'[%give to=0xd6dc.c8ff.7ec5.4416.6d4e.b701.d1a6.8e97.b464.76de amount=123.456 item=0x89a0.89d8.dddf.d13a.418c.0d93.d4b4.e7c7.637a.d56c.96c0.7f91.3a14.8174.c7a7.71e6 `0xd79b.98fc.7d3b.d71b.4ac9.9135.ffba.cc6c.6c98.9d3b.8aca.92f8.b07e.a0a5.3d8f.a26c]\']' ~] [%poke [rollup-host %uqbar %wallet-poke '[%submit from=0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70 hash=0xa99c.4c8e.1c8d.abb8.e870.81e8.8c96.2cf5 gas=[rate=1 bud=1.000.000]]'] ~] [%dojo [~nec ':sequencer|batch'] `(list test-read-step:zig)`~[[%custom-read %scry-indexer '/newest/item/0x89a0.89d8.dddf.d13a.418c.0d93.d4b4.e7c7.637a.d56c.96c0.7f91.3a14.8174.c7a7.71e6/noun' '']]]]
:ziggurat &ziggurat-action [%foo %add-test `%send-nec-custom send-nec-custom]

=setup-id 0xa253.baf1.f666.df41.ab31.fe25.2de6.5d20
=scry-nec-id 0xa2d1.13bb.100c.267f.9357.209d.d428.c33e
=scry-bud-id 0xddd5.d31d.72c2.dbe0.42fe.7ae1.3d17.8db5
=scry-clay-id 0x29de.35b5.a26d.c49c.a39c.7437.c399.c316
=send-nec-id 0x49.6b9f.c2dc.2641.5c66.e64a.848b.80ee
=send-nec-custom-id 0x4a0c.8a95.d289.95f3.c455.791c.8431.d24d

:ziggurat &ziggurat-action [%foo %start-pyro-ships ~]

:ziggurat &ziggurat-action [%foo %run-test setup-id]


::  wait until init-ship and setup is done

:ziggurat &ziggurat-action [%foo %run-test send-nec-custom-id]
:ziggurat +dbug [%state %test-queue]
:ziggurat &ziggurat-action [%foo %run-test scry-bud-id]
:ziggurat +dbug [%state %test-queue]
:ziggurat &ziggurat-action [%foo %run-test scry-nec-id]
:ziggurat +dbug [%state %test-queue]
:ziggurat &ziggurat-action [%foo %run-test scry-clay-id]
:ziggurat +dbug [%state %test-queue]
```

you will note that the tests get run out of order because they never go to queue. What is happening is the first test is sent, and is popped off queue to be run; then while it is running, the second test is sent, sees nothing on queue, so run starts, ... etc.

I think we need to bring back the `is-running=?` %ziggurat state. When we are running a test it is `%.y`, when a test completes, it is `%.n`. If we get a request to `%run-test` while it is `%.y`, we add that test to the queue.

I think the above is the right way to do it. My initial thought was "just remove %run-test", but as I comment above in one of the comment threads, I think we will want to be aggressively running the queue, e.g. always pairing a %run-queue whenever we %add. This will run into the same trouble as the example I give above unless we add a `is-running=?` state.

Open to alternative suggestions to fix.

2022-11-24 21:35 UTC, tadad commented
I knew this behavior could happen but didn't think it was an issue - just tested these commands myself and all the tests definitely start and finish - they are are started in the right order, but they don't necessarily finish in the right order, which seems fine to me.

The idea that multiple tests can run at once seems fine, though if that is the case then we could get rid of the queue and just have a set of tests to run, and start a bunch of threads that will finish at indeterminate times

2022-11-24 21:55 UTC, tadad commented
though now that I think about it this won't work that well - if two tests touch the same piece of state then there will be a problem, so we should run these in serial

which brings up another point - I don't think we have built the thing to do like a javascript `beforeEach` so that the state resets every test. What we want is like the `setup` test step to be snapshotted and restored at the start of every test

2022-11-24 23:04 UTC, tadad commented
last bug fixed

2022-11-26 22:16 UTC, hosted-fornet commented
> though now that I think about it this won't work that well - if two tests touch the same piece of state then there will be a problem, so we should run these in serial

This was my thinking as well. It is much easier for a user to understand what is going on if everything is in serial.

> which brings up another point - I don't think we have built the thing to do like a javascript `beforeEach` so that the state resets every test. What we want is like the `setup` test step to be snapshotted and restored at the start of every test

Yeah, I have it set up so that snapshotting happens at the end of each test step, so you will have, e.g., `/foo/setup-id/0`, and so on for each project/test-id/test-step, see https://github.com/uqbar-dao/uqbar-core/blob/95d6cf62ac13733f9cb01bad26e614f29a137883/ted/ziggurat/test/run.hoon#L104 

I think you are right that it will often be the case that the user will want to reset to the setup state before running. You can also imagine a user might want to do test steps A, then B, then C, without resetting state. I leave that for the frontend guys to figure out how to display those options (and the current state) nicely on the UI: we just need to make sure the snapshots are where they expect them to be and are easily restored, etc.

I suspect we also have some more thinking to do about how best to surface state for the FE to display in general. I mean not just what the user has scried/subscribed to, etc., but also maybe more general state of agents touched, chain state, stuff like that. We can make it easy for the user to query stuff as well with `:pyro|dojo ...`, but just having some type of recently touched state dashboard" would be super cool.

2022-11-28 20:06 UTC, hosted-fornet approved these changes
LGTM, tests work as expected, nice work :+1:

2022-11-28 20:13 UTC, merged