Da/subscribe
uqbar-dao/uqbar-core pull request #314
Opened 2022-12-02 20:51 UTC by tadad

2022-12-02 21:11 UTC, tadad commented
A few things in this PR
- basic subscription testing working
  - This is just a simple first draft that let's you verify that a subscription was received by an agent on another ship
- caching of ship snapshots
  - doesn't work fully because of a zuse mismatch, but the problem gets fixed in [this](https://github.com/urbit/urbit/pull/6044) PR, so it'll work soon.
- updates to the README

2022-12-05 21:09 UTC, hosted-fornet requested changes

2022-12-05 21:09 UTC, hosted-fornet commented on app/subscriber.hoon
> +    ``noun+!>((~(got by signs.state) [ship app paf]))
It might be nice to change this to return the `get by` to avoid crashing? E.g. try

```
=my-test-2 [[%read-subscription [~bud ~nec %rollup /not-a-sub-path/noun] '']]~
:ziggurat &ziggurat-action [%foo %add-and-queue-test `%my-test-2 ~[/zig/sur/zig/indexer/hoon] my-test-2]
:ziggurat &ziggurat-action [%$ %run-queue ~]
```

2022-12-05 21:09 UTC, hosted-fornet commented on ted/ziggurat/test/run.hoon
> +    (pure:m !>(~))
I would recommend not using `~` to indicate success:

1. It interferes with line 102 above, where if we get a `~` result from scry we are informing caller that our scry was successful: this is wrong.
2. It means we place a `~` in the `result` field of a `test-result`. We should always have `expected.test-result == result.test-result` if `success=%.y`. The reason is that we may (or users may) make use of the `result.test-result`, and so it should be a predictable value when `success=%.y`, and not vary its semantics based on which test step type has produced it.

2022-12-05 21:09 UTC, hosted-fornet commented on ted/ziggurat/test/run.hoon
> +    ::  transform to qeu, cut it at the
Remove old comment.

2022-12-05 21:09 UTC, hosted-fornet commented on ted/ziggurat/test/run.hoon
> +    =/  res-text=@t  (crip (noah result)) :: TODO probably wrong
Would be nice to `tap by` the `set` when we fail to find our `expected` (perhaps that should happen above near line 100? Not sure). The reason is that it will be simpler to parse for us or for FEs: `set`s get displayed in the `n l r` form.

2022-12-05 21:09 UTC, hosted-fornet commented on ted/ziggurat/test/run.hoon
> +      ~|("ziggurat-test-run: %poke expected can only contain %scrys, %subscribes, %waits" !!)
Change text since we are in `%subscribe` here

2022-12-05 21:09 UTC, hosted-fornet commented on ted/ziggurat/test/run.hoon
> +  =+  fact-set=(need ;;((unit (set @t)) scry-noun))
We should probably not use `+need` here, since it crashes on fail. Instead can go a `?~` or something. If we remove `~` return meaning success as suggested below on line 105, could do something like

`?~  fact-set  (pure:m !>(~))`

The reason we should avoid crashes if possible is so that even if one test-step fails, we can still attempt to run others.

2022-12-05 21:44 UTC, tadad commented on app/subscriber.hoon
> +    ``noun+!>((~(got by signs.state) [ship app paf]))
changed it to this because I don't want to unwrap a unit
```
    :^  ~  ~  %noun
    =+  (~(get by signs) [ship app paf])
    ?@  -  !>(~)  !>((need -))
```

2022-12-06 06:18 UTC, hosted-fornet approved these changes
Some comments on readme and a few nits, otherwise LGTM, nice work :+1: 

PS: oh, also please update the pill before merging.

2022-12-06 06:18 UTC, hosted-fornet commented on app/subscriber.hoon
> +    ?@  -  !>(~)  !>((need -))
nit: Slight preference to use `?~` or something else here that denotes we are checking if it is `~`, rather than `@`: better to be explicit than implicit.

2022-12-06 06:18 UTC, hosted-fornet commented on app/ziggurat.hoon
> +      ::     effects are a different subscribe path
I'm not really sure what this comment is about. Do you want to discuss/address this on this PR or on a subsequent PR when we get snapshots working more robustly?

2022-12-06 06:18 UTC, hosted-fornet commented on ted/ziggurat/test/run.hoon
> +  (pure:m !>((crip (noah !>(~(tap in fact-set))))))
We may need to come back to this, but it is good for now. My concern looking at the output is that we can't `+ream` it because it is in the `wain` form.

2022-12-06 16:32 UTC, tadad commented on readme-pyro.md
> +|unmount %zig
is there another way to push a desk down to unix?

2022-12-06 16:36 UTC, tadad commented on app/ziggurat.hoon
> +      ::     effects are a different subscribe path
no this comment is wrong - I think I misunderstood /restore whenever I wrote it

2022-12-06 16:42 UTC, merged