misc. %pyro fixes
uqbar-dao/uqbar-core pull request #365
Opened 2023-01-05 19:37 UTC by tadad

**Problem**:
pyro code isn't clean
pyro needs more tooling
other misc fixes to run.hoon and ziggurat

**Solution**:
refactor it
comment it, remove superfluous comments
add more generators
add more helpers to lib/pyro
remove useless scries, refactor remaining ones

**Notes**:
@hosted-fornet only need a review on ziggurat.hoon and run.hoon

2023-01-06 16:24 UTC, tadad commented
@hosted-fornet do you want me to start working on swapping these subscriptions out in run/hoon thread?

2023-01-09 17:52 UTC, tadad commented on ted/ziggurat/test/run.hoon
> -    $
`next-events` will always be empty because that's how `+plow-all` works

2023-01-09 17:55 UTC, tadad commented on app/pyro.hoon
> -      |=([p=pier] =(0 ~(wyt in next-events.p)))
it will always be empty

2023-01-13 07:26 UTC, hosted-fornet requested changes
A couple of things I'd like addressed -- otherwise just a couple questions and notes to our future selves.

To explain a bit more about my style comments: my general policy is that when modifying existing code, I try to follow the style in that piece of code. Ideally, a whole repo has the same style -- but this is hard to maintain without a lot of discipline and agreement amongst contributors and I don't think its a reasonable goal for Uqbar right now. Since we don't have a code style guide and are moving fast, I just aim to follow whatever file I am in.

2023-01-13 07:26 UTC, hosted-fornet commented on app/pyro.hoon
> +      [pier-data(processing-events %.y) (~(get ja unix-boths) who)]
Is the reason for this change the switch in the default `processing-events` here?:

https://github.com/uqbar-dao/uqbar-core/blob/c5f070decd8da53b04ce0601de1da0dac9a04a02/app/pyro.hoon#L34

2023-01-13 07:26 UTC, hosted-fornet commented on app/pyro.hoon
> +    =/  poke-arm  (mox +23.snap) :: see +poke in arvo.hoon
Good comment :+1:

2023-01-13 07:26 UTC, hosted-fornet commented on sur/zig/pyro.hoon
> -      [%pill =pill]
Just noting here that removing %pill from %pyro-action means we will have to write its own mark file if we wish to make this accessible from FE. For now, this is fine since I don't think we have plans to make this accessible from FE (something we should either update periodically in OTAs or a bit of a poweruser feature).

2023-01-13 07:26 UTC, hosted-fornet commented on lib/zig/pyro.hoon
> +::
Just noting here that we should check in sometime down the road to see if we've made use of these gates.

2023-01-13 20:25 UTC, hosted-fornet commented
FYI @0x70b1a5 a number of changes here to %pyro scry interface, so if you are using %pyro scries, you should take a look at this PR.

https://github.com/uqbar-dao/uqbar-core/blob/d1727d0925a780659e2b6ccb5c1b6028beb5009d/sur/zig/pyro.hoon#L51-L56

https://github.com/uqbar-dao/uqbar-core/blob/d1727d0925a780659e2b6ccb5c1b6028beb5009d/app/pyro.hoon#L107-L124

2023-01-13 20:26 UTC, merged