Da/type
uqbar-dao/uqbar-core pull request #379
Opened 2023-01-13 20:26 UTC by tadad

**Problem**:
pyro isn't typed

**Solution**:
run it all in vase mode

**Notes**:

2023-01-17 05:12 UTC, hosted-fornet requested changes
Left some comments. Aside from those, I think there is a little more work required here because of what you note in the header of gen/pyro/scry. E.g., consider a test scry I ran:
```hoon
> .^(noun %gx /=pyro=/i/~nec/cx/~nec/base/(scot %da now)/desk/bill/bill)
[ 1.701.667.681
  29.401.445.273.533.025
  1.735.746.148
  1.869.246.308
  138.296.428.078.681.297.420.579.941
  1.685.024.616
  1.836.213.608
  1.936.614.764
  1.735.289.200
  125.779.801.895.027
  0
]
```

The type is `wain`, but if I put it as the first argument, it crashes:
```hoon
> .^(wain %gx /=pyro=/i/~nec/cx/~nec/base/(scot %da now)/desk/bill/bill)
bail: 4
drum: link [~nec %dojo]
[%dojo-peer-replaced ~.drum_~nec]
[unlinked from [p=~nec q=%dojo]]
/gx/~nec/pyro/~2023.1.17..05.05.31..e9a1/i/~nec/cx/~nec/base/~2023.1.17..05.05.31..e9a1/desk/bill/bill
[%drum-coup-fail ~nec p=~nec q=%dojo]
[linked to [p=~nec q=%dojo]]
```

Once this is working, this PR will be done, but still not yet ready to merge: I need to integrate the changes into %ziggurat before we merge this or we'll have a broken state on next/pyro. I'll make integration a high priority once this PR is done.

2023-01-17 05:12 UTC, hosted-fornet submitted a review, later dismissed
Left some comments. Aside from those, I think there is a little more work required here because of what you note in the header of gen/pyro/scry. E.g., consider a test scry I ran:
```hoon
> .^(noun %gx /=pyro=/i/~nec/cx/~nec/base/(scot %da now)/desk/bill/bill)
[ 1.701.667.681
  29.401.445.273.533.025
  1.735.746.148
  1.869.246.308
  138.296.428.078.681.297.420.579.941
  1.685.024.616
  1.836.213.608
  1.936.614.764
  1.735.289.200
  125.779.801.895.027
  0
]
```

The type is `wain`, but if I put it as the first argument, it crashes:
```hoon
> .^(wain %gx /=pyro=/i/~nec/cx/~nec/base/(scot %da now)/desk/bill/bill)
bail: 4
drum: link [~nec %dojo]
[%dojo-peer-replaced ~.drum_~nec]
[unlinked from [p=~nec q=%dojo]]
/gx/~nec/pyro/~2023.1.17..05.05.31..e9a1/i/~nec/cx/~nec/base/~2023.1.17..05.05.31..e9a1/desk/bill/bill
[%drum-coup-fail ~nec p=~nec q=%dojo]
[linked to [p=~nec q=%dojo]]
```

Once this is working, this PR will be done, but still not yet ready to merge: I need to integrate the changes into %ziggurat before we merge this or we'll have a broken state on next/pyro. I'll make integration a high priority once this PR is done.

2023-01-17 05:17 UTC, hosted-fornet commented
Sorry for the double-post. Internet issues.

One additional thing I forgot to add: there are semantics for the (unit (unit cage)) returned by scry (i.e. `~` means something different from `[~ ~]`), so let's double check to make sure we are following them: https://developers.urbit.org/guides/core/app-school/10-scry#handling-scries

https://github.com/uqbar-dao/uqbar-core/blob/eebc0480b920748f1382b0faece2a5c969a51773/app/pyro.hoon#L134

https://github.com/uqbar-dao/uqbar-core/blob/eebc0480b920748f1382b0faece2a5c969a51773/app/pyro.hoon#L275

2023-01-17 18:58 UTC, tadad commented
> One additional thing I forgot to add: there are semantics for the (unit (unit cage)) returned by scry (i.e. ~ means something different from [~ ~]), so let's double check to make sure we are following them: https://developers.urbit.org/guides/core/app-school/10-scry#handling-scries

we are following them:
`~` = ship not found, so scry path doesn't exist
`[~ ~]` = ship found and ship crashed on trying to execute the scry (within the virtual ship this could either mean a `~` or `[~ ~]` was returned, but we don't have access to whether it was one or the other
`(unit (unit cage))` = ship successfully executed the scry

2023-01-17 18:59 UTC, tadad commented on app/pyro.hoon
> +    ::  TODO type is a vase, so q.res is a noun. Should be molded somehow
wish is basically never used except by the runtime to make sure the kelvin versions match. I have some ideas for using it more, but until then we can leave it like this

2023-01-17 19:05 UTC, tadad commented on app/pyro.hoon
> +      (mule |.((slam [-:!>(poke:arvo-adult) poke:snap] !>([tym ue]))))
nice

2023-01-17 19:15 UTC, tadad commented on app/pyro.hoon
> +  !<(typ [-:!>(*typ) val])
not exactly, `;;` is about molding while `+hole`, `!>`, `!<`, etc. are about types. Our goal isn't to mold everything, but to type everything so that we can `+slam` instead of `+slum` to get type information out.

2023-01-17 19:17 UTC, hosted-fornet commented
> > One additional thing I forgot to add: there are semantics for the (unit (unit cage)) returned by scry (i.e. ~ means something different from [~ ~]), so let's double check to make sure we are following them: https://developers.urbit.org/guides/core/app-school/10-scry#handling-scries
> 
> we are following them: `~` = ship not found, so scry path doesn't exist `[~ ~]` = ship found and ship crashed on trying to execute the scry (within the virtual ship this could either mean a `~` or `[~ ~]` was returned, but we don't have access to whether it was one or the other `(unit (unit cage))` = ship successfully executed the scry

Ok, cool, thanks for confirming.

2023-01-17 19:19 UTC, tadad commented on app/pyro.hoon
> +    =.  snap  (hole _arvo-adult +.q.p.poke-result)
yeah exactly

2023-01-17 21:19 UTC, tadad commented
on the issue of the bug - we should be molding the the inner scry when we do a peek. We have two marks - and so we should have two molds as well, but we don't. So we need to mold inside of `+scry`. Verified that the bug gets fixed if I mold inside `+scry`, but not sure what the general solution is yet (or if it exists)

2023-01-18 02:58 UTC, hosted-fornet commented on app/pyro.hoon
> +    (slam !>(|=(u=(unit (cask)) (tail (need u)))) p.pek)
Still hard to read as of a146cbc. Maybe space the lines out on multiple lines?

2023-01-18 02:59 UTC, hosted-fornet commented on app/pyro.hoon
> +    :: is there a way to speed it up?
Bump -- maybe this is dumb, but I'd be happier knowing for sure by testing that it is dumb than accepting a slowdown without trying to get around it.

2023-01-18 15:35 UTC, tadad commented
@hosted-fornet the scry interface hasn't changed except for `gen/pyro/scry.hoon` which I updated to be more like `+scry` in `strandio.hoon`. The main difference is that you can get things out using marks other than just `noun`. This can be a bit buggy and molds also seem like a problem until further notice

2023-01-18 15:50 UTC, tadad commented on app/pyro.hoon
> +    (slam !>(|=(u=(unit (cask)) (tail (need u)))) p.pek)
I tried that and I don't think it really helped the readability. I'll add an extra comment

2023-01-18 15:51 UTC, tadad commented on app/pyro.hoon
> +    :: is there a way to speed it up?
the slowdown is on the order of like miliseconds, just like a slight hiccup. Doesn't feel unbearably slow. I do have to slam so just figured I would leave a comment for the future in case I figure something out

2023-01-18 17:49 UTC, hosted-fornet commented on app/pyro.hoon
> +    :: is there a way to speed it up?
Cool, thanks for confirming.

2023-01-18 17:51 UTC, hosted-fornet commented
Okay, I will try running with %ziggurat today, and if that goes well without hiccups we can merge. I am just cautious because I saw some weirdness related to the double /noun at the end, where both need to be the same or problems happen, so I want to suss out any behaviors like that before we merge.

2023-01-19 05:54 UTC, hosted-fornet commented
Started work to integrate with %ziggurat in https://github.com/uqbar-dao/uqbar-core/pull/387

Ran into an issue with one scry. The "normal" scry is
```hoon
.^((set @tas) %cd /=base=)
```
and I can get it to work with `:pyro|dojo` as well. But translating it to `/i` form has just been crashing. The one I thought should work is simply:
```hoon
.^(* %cd /=pyro=/i/~nec/cd/~nec/base/(scot %da now)/noun)
```
but that crashes. Adding an additional `/noun` to the end or removing the current one crashes as well. What is going on here?

2023-01-19 23:06 UTC, hosted-fornet commented
> Started work to integrate with %ziggurat in #387
> 
> Ran into an issue with one scry. The "normal" scry is
> 
> ```hoon
> .^((set @tas) %cd /=base=)
> ```
> 
> and I can get it to work with `:pyro|dojo` as well. But translating it to `/i` form has just been crashing. The one I thought should work is simply:
> 
> ```hoon
> .^(* %cd /=pyro=/i/~nec/cd/~nec/base/(scot %da now)/noun)
> ```
> 
> but that crashes. Adding an additional `/noun` to the end or removing the current one crashes as well. What is going on here?

Bump @tadad : any ideas on this or does this require code changes here? This is a blocker for %ziggurat integration and getting this PR merged.

2023-01-19 23:31 UTC, tadad commented
imo I think we should just wait because the changes I'm building on top of this PR (quickboot) are wrecking a lot of stuff

2023-01-19 23:39 UTC, hosted-fornet commented
Sounds good.

2023-01-25 17:19 UTC, tadad commented
> .^(* %cd /=pyro=/i/~nec/cd/~nec/base/(scot %da now)/noun)
@hosted-fornet realized this error ^ is because the care has to be `%gx`
`.^(* %gx/=pyro=/i/~nec/cd/~nec/base/(scot %da now)/noun)` works

2023-01-26 00:15 UTC, hosted-fornet requested changes
%init-ship is blazingly fast: really excellent work!

Scrying is more restrictive here than it was before. For example, on next/pyro
```hoon
.^(* %gx /=pyro=/i/~nec/ge/~nec/base/(scot %da now)/noun)
```
works fine, whereas here, it does not work unless I change the trailing mark to `/app`:
```hoon
.^(* %gx /=pyro=/i/~nec/ge/~nec/base/(scot %da now)/apps)
```

This is a little worse for %ziggurat users, because we can no longer just append a `/noun` programatically and have them give the scry as they'd call it on a normal ship (no doubled `/mark/mark`). It also means we have to message clearly that the user must specify the double `/mark/mark` in cases where they do not have a mar file with a mark -> noun arm.

Is there a way to get back to `/noun` like we had on next/pyro?

My other main concern with this PR is that we are moving the slow boot time to a slow initial `|install` time because we have to rebuild the kernel:
```hoon
gall: installing %uqbar
gall: installing %rollup
gall: installing %sequencer
gall: installing %indexer
gall: installing %wallet
gall: installing %pyro
gall: installing %pyre
gall: installing %ziggurat
[%pyro %unknown-effect ~nec wire=/http-server/0v1n.2m9vh card=[p=%set-config q=[0 1 0 0]]]
[%pyro %unknown-effect ~nec wire=/newt/0v1n.2m9vh card=[p=%turf q=0]]
clay: kernel updated
clay: rebuilding %base after kernel update
gall: installing %acme
gall: installing %azimuth
gall: installing %dbug
gall: installing %dojo
gall: installing %eth-watcher
gall: installing %hood
drum: link [~nec %dojo]
kiln: boot
gall: installing %herm
gall: installing %lens
gall: installing %ping
gall: installing %spider
[%pyro %killing ~nec]
"~wes: > |install our %zig"
"~wes: >="
```

@tadad you've said we are waiting on https://github.com/urbit/urbit/pull/6044 to mitigate this. Does this mean once 6044 is merged we will no longer have to rebuild the kernel?

2023-01-26 03:37 UTC, tadad commented on app/pyro.hoon
> +    :: =.  park  (park:pyro our.bowl %base %da now.bowl)
later

2023-01-26 03:37 UTC, tadad commented on app/pyro.hoon
> +          park=task:clay :: TODO should be $>(%park task:clay)
later. Not sure how/if it can be fixed

2023-01-26 03:37 UTC, tadad commented on lib/zig/pyro.hoon
> +  ::  TODO move to note-arvo?
later

2023-01-26 03:37 UTC, tadad commented on lib/zig/pyro.hoon
> +::  TODO might refactor this back into +park, less code...
later

2023-01-26 03:38 UTC, tadad commented on app/pyre.hoon
> +  [%pass / %agent [our dap]:bowl %poke %pyre-action !>([%resub ~])]~
nice catch

2023-01-26 03:39 UTC, tadad commented on lib/zig/pyro.hoon
> +:: TODO broken
not actually broken, removed comment

2023-01-26 03:39 UTC, tadad commented on app/pyro.hoon
> +          [/e/http-server/0v1n.2m9vh %live 8.080 `8.445]  :: TODO do we need this event
later

2023-01-26 03:42 UTC, tadad commented
yeah we are frontloading the cache building to on-init, I don't think it's a huge deal. We actually need [this branch](https://github.com/urbit/urbit/tree/jt/boot) merged before I can speed up on-init, so might work on that in the coming weeks.

2023-01-26 04:06 UTC, tadad commented
as for the scries I'm not convinced that moving back to the old system is better. That would mean you could *only* get out nouns, as opposed to all marks. As a general principle I don't believe in limiting functionality just because some people might not understand what they're doing. Plus the error messages tell you exactly what to do - e.g. `[%error-building-tube %noun %apps]`

2023-01-26 18:39 UTC, hosted-fornet commented
> yeah we are frontloading the cache building to on-init, I don't think it's a huge deal. Having a slow install is not the end of the world, and the only other option is to have a slow initial first-ship-boot, which is worse imo. We actually need [this branch](https://github.com/urbit/urbit/tree/jt/boot) merged before I can speed up on-init, so might work on that in the coming weeks.

Both are pretty bad, since for all practical purposes we need to `|install` stuff on fakeships. Can you give me a specific expectation for how we will reduce the initial `|install` time? E.g., will the O(1) commits help, or is that just for commits and not installs? And what is the path from the jt/boot branch to faster initial `|install` times? We can talk on the call tomorrow rather than here in the comments -- I just want to understand the path forward.

2023-01-26 18:43 UTC, tadad commented
what are you talking about? it's only %pyro's on-init that's slowed down - and why do we need to install %pyro (or ziggurat for that matter) on fake ships?

2023-01-26 18:44 UTC, hosted-fornet commented
> as for the scries I'm not convinced that moving back to the old system is better. That would mean you could _only_ get out nouns, as opposed to all marks. As a general principle I don't believe in limiting functionality just because some people might not understand what they're doing. Plus the error messages tell you exactly what to do - e.g. `[%error-building-tube %noun %apps]`

The current state is you have to apply the correct mark, but you still only ever get the noun out, which is strictly worse than the old system, where you could always apply noun mark (easier UX) and only ever get noun out. Once we have real marks out, I agree it will be better. But compare this to scrying non-virtualships: I can always put a `/noun` mark and get back a result. We are now requiring the user to break with what they are used to on non-virtualships. I won't hold up this PR because of this, but we need to make an issue to make scries actually work with molding, i.e.

```hoon
.^(@t %cx /=base=/app/spider/hoon)
```

should work -- as opposed to right now where we need to

```hoon
;;  @t  .^(* %cx /=base=/app/spider/hoon)
```

2023-01-26 18:45 UTC, hosted-fornet requested changes
Let me do one more round of testing with %ziggurat integration and then we can merge both PRs.

2023-01-26 18:46 UTC, hosted-fornet commented
> what are you talking about? it's only %pyro's on-init that's slowed down - and why do we need to install %pyro (or ziggurat for that matter) on fake ships?

Oh I see, this is good information -- I hadn't realized this distinction. We certainly need to install chain stuff on virtualships, so perhaps once we break this repo apart into chain and dev suite this problem will go away.

2023-01-26 18:47 UTC, hosted-fornet commented
> what are you talking about? it's only %pyro's on-init that's slowed down - and why do we need to install %pyro (or ziggurat for that matter) on fake ships?

Specifically what I was seeing was installs of %zig requiring a rebuild of the kernel. I will play around with the desk.bill to see if I can get this to install without rebuilding the kernel.

2023-01-26 18:53 UTC, tadad commented
> which is strictly worse than the old system
this scry used to be impossible:
```
> (json .^(* %gx /=pyro=/i/~nec/gx/~nec/pyro/i/ships/json/json))
[%o p={[p='ships' q=[%a p=~]]}]
```

2023-01-26 18:57 UTC, hosted-fornet commented
> what are you talking about? it's only %pyro's on-init that's slowed down - and why do we need to install %pyro (or ziggurat for that matter) on fake ships?

Confirmed that you are correct about this -- so we either need to separate out the repos or be clever with desk.bill and `|start`ing apps on devship / virtualships to avoid this slowdown. Because we are certainly installing chain stuff on virtualships by default.

2023-01-26 19:00 UTC, tadad commented
> > what are you talking about? it's only %pyro's on-init that's slowed down - and why do we need to install %pyro (or ziggurat for that matter) on fake ships?
> 
> Confirmed that you are correct about this -- so we either need to separate out the repos or be clever with desk.bill and `|start`ing apps on devship / virtualships to avoid this slowdown. Because we are certainly installing chain stuff on virtualships by default.

it's time to separate ziggurat+pyro from uqbar-core

2023-01-26 19:05 UTC, hosted-fornet commented
> > which is strictly worse than the old system
> 
> this scry used to be impossible:
> 
> ```
> > (json .^(* %gx /=pyro=/i/~nec/gx/~nec/pyro/i/ships/json/json))
> [%o p={[p='ships' q=[%a p=~]]}]
> ```

Good point, that is a case I hadn't considered.

2023-01-26 19:24 UTC, hosted-fornet approved these changes
Excellent work, let's get this merged :+1:

2023-01-26 19:25 UTC, merged